# Generated by Django 4.0.1 on 2022-03-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='area',
            field=models.CharField(choices=[('one', 'استان تهران یا البرز'), ('two', 'دیگر استان ها')], default='استان تهران یا البرز', max_length=20, verbose_name='محدوده'),
        ),
    ]
