# Generated by Django 4.0.1 on 2022-03-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_buy_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی'),
        ),
    ]
