# Generated by Django 4.0.1 on 2022-03-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_buy_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='satteled',
            field=models.BooleanField(default=False),
        ),
    ]
