# Generated by Django 4.0.1 on 2022-03-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_buy_satteled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='نام هنرمند')),
                ('avatar', models.ImageField(default='product.jpeg', null=True, upload_to='', verbose_name='عکس هنرمند')),
                ('des', models.TextField(null=True, verbose_name='مشخصات')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.artist', verbose_name='آفریننده'),
        ),
    ]
