# Generated by Django 4.0.1 on 2022-03-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_artist_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='section',
            field=models.CharField(max_length=100, null=True, verbose_name='دسته ی هنری'),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('painting', 'نفاشی و طراحی'), ('writing', 'خط'), ('sculpture', 'مجسمه'), ('photography', 'عکس'), ('mosaic', 'معرق'), ('fasion', 'طراحی لباس')], default=1, max_length=60, verbose_name='شاخه'),
            preserve_default=False,
        ),
    ]
