# Generated by Django 4.0.1 on 2022-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_alter_artist_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('one', 'اثر هنری'), ('two', 'کالای فروشگاهی')], max_length=60, null=True, verbose_name='نوع محصول'),
        ),
    ]
