# Generated by Django 4.0.1 on 2022-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_menucat_menuitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav',
            field=models.TextField(blank=True, null=True, verbose_name='علاقمندی ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سطح بازی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mafia_games',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد بازی ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه'),
        ),
    ]
