# Generated by Django 4.0.1 on 2022-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
