# Generated by Django 4.0.1 on 2022-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد دستگاه'),
        ),
    ]
