# Generated by Django 4.0.1 on 2022-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0017_orderitem_total_price_alter_orderitem_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=100, null=True, verbose_name='قیمت نهایی فاکتور'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.CharField(max_length=100, null=True, verbose_name='قیمت نهایی محصول'),
        ),
    ]
