# Generated by Django 4.0.1 on 2022-04-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0022_remove_orderitem_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.orderitem', verbose_name='سفارش'),
        ),
    ]
