# Generated by Django 4.0.1 on 2022-04-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0023_menuitem_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order_item',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.orderitem', verbose_name='سفارش'),
        ),
    ]
